### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by ManewTeng** [exejar/Weave-Manager#8]
How does this work, I launched Minecraft version 1.8.9 but it doesn't seem to detect what to do? don't is Lunar.

**Comment by exejar** [comment]
I'm not quite sure what you are asking. Are you using [Lunar Launcher Inject](https://github.com/Nilsen84/lunar-launcher-inject) to launch with Weave?

**Comment by ManewTeng** [comment]
No I'm using mineraft1.8.9 Forge version.But is doesn't seem to have detected.
![Snipaste_2023-07-10_13-48-19](https://github.com/exejar/Weave-Manager/assets/122134399/832f68a2-706a-4410-aca9-a56e51159992)

**Comment by ManewTeng** [comment]
But the vanilla version doesn't work either.

**Comment by exejar** [comment]
I understand now. We have rewritten Weave-Manager and are currently finishing it up. A new release will be created soon. Also, we are currently working to support Forge and Vanilla, currently they do not work with Weave but will soon. Join the discord for updates. https://discord.com/23TQpHgzNt
